### ISSUE TITLE
Best way of serving landing page background videos

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#1]
Should we host, display via html <video>? 
Stream from vimeo, youtube, etc? 
How big is too big for filesize?

**Comment by streeetlamp** [comment]
http://stackoverflow.com/questions/10328401/html5-how-to-stream-large-mp4-files

**Comment by streeetlamp** [comment]
Video src should be set via JS so we can feature detect / not display or download video at all for mobile users 

http://stackoverflow.com/questions/28605591/prevent-html5-videos-from-downloading-the-files-on-mobile-videojs

**Comment by luetkemj** [comment]
Good call. 
Currently we are spitting out all the markup instead of just setting the url.

Must fix.

**Comment by streeetlamp** [comment]
http://www.designer-daily.com/fullscreen-background-videos-15-websites-that-get-it-right-52168
