### ISSUE TITLE
A better search

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#10]
WP search sucks, we need to use something better. 
A custom google search appliance thing is a promising idea that we have experience with. 

![giphy-2](https://cloud.githubusercontent.com/assets/1740634/6968749/0759dc58-d937-11e4-8b5e-cb63949110c2.gif)

**Comment by streeetlamp** [comment]
pricing 
![screen shot 2015-04-02 at 12 58 43 pm](https://cloud.githubusercontent.com/assets/1740634/6968852/09d5a0b0-d938-11e4-9dfa-6f3fda8506a0.png)

**Comment by streeetlamp** [comment]
http://artsy.github.io/blog/2014/10/23/how-we-customized-google-site-search-at-artsy/

**Comment by streeetlamp** [comment]
A basic custom google search using their API has been implemented. To improve it, we need to be adding custom open graph meta tags (http://ogp.me/) as described in the artsy article above

**Comment by dstrogiy** [comment]
Tweaks to do that are not related to the actual search area:

- [ ] Add dark overlay on body when search is open
- [ ] Close buton finesse
- [ ] Ability to close by clicking anywhere on the page outside of search area

**Comment by dstrogiy** [comment]
- [ ] search on mobile - interferes with the current mobile nav

**Comment by dstrogiy** [comment]
Search should probably be filtered for input - currently you can stick any html code inside it

![screen shot 2015-06-24 at 3 20 01 pm](https://cloud.githubusercontent.com/assets/6132788/8339319/882821da-1a84-11e5-87b8-22eb736d6373.png)

**Comment by dstrogiy** [comment]
- [ ] homepage search overlay - doesn't cover video 100%

**Comment by dstrogiy** [comment]
- [ ] search results should be links
- [ ] pagination
- [ ] input needs to work in the search popup

**Comment by dstrogiy** [comment]
![thx11](https://cloud.githubusercontent.com/assets/6132788/8727668/deab35f2-2bae-11e5-975b-c4580ee8a62d.gif)

works & looks güd
just need dat premium package
