### ISSUE TITLE
Cache External API Feeds [ juicer, calendar ]

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#100]
Really no need to force the user to fetch those every page load, hopefully easy enough to do it with the server and cache them.

http://stackoverflow.com/questions/21806992/how-to-cache-an-external-json-request

**Comment by dstrogiy** [comment]
![tumblr_nj9oq1qznb1traht2o1_500](https://cloud.githubusercontent.com/assets/6132788/8883622/3ba056fa-321e-11e5-8da6-f21150340d71.gif)

**Comment by streeetlamp** [comment]
blessings on blessings

**Comment by streeetlamp** [comment]
![popkey-thank_you](https://cloud.githubusercontent.com/assets/1740634/8940339/520cfc1a-3537-11e5-96b9-dc23706da1e5.gif)

thank you localstorage
