### ISSUE TITLE
Upcoming events in sidebar recurring event date

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#107]
![screen shot 2015-07-29 at 1 20 29 pm](https://cloud.githubusercontent.com/assets/6132788/8964632/ac4018a8-35f4-11e5-8828-43ad5d1c5c5b.png)

Needs same treatment as on homepage, with both start & end dates showing

**Comment by streeetlamp** [comment]
oh yeahh, forgot about these nuggets

**Comment by streeetlamp** [comment]
yessir 

![popkey-mlb-major](https://cloud.githubusercontent.com/assets/1740634/8966333/d5209cca-35fe-11e5-862e-85ff894b9ef9.gif)
