### ISSUE TITLE
Site Wide Alert Messaging

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#108]
Need some ACF stuffs added to the options panel that allows a very important messages to be added site wide to the top of the page. 

I think it can have a few options for how the message should be styled. For example, notice, alert, emergency. 

Simple example: 
![emergency-alert-banner](https://cloud.githubusercontent.com/assets/1740634/8964764/7e106586-35f5-11e5-9a12-7c298e68697f.jpg)

**Comment by dstrogiy** [comment]
The styles are all there, just need the ACF implementation

**Comment by streeetlamp** [comment]
![jzfo2rt](https://cloud.githubusercontent.com/assets/1740634/8992068/85f9adfe-36ca-11e5-80c2-e26cb3876d58.gif)
