### ISSUE TITLE
Blocks & Their Options

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#11]
A default standard block spans 100% of it's parent, has a transparent background, black text color, black border, padding inside and a margin above it.

**Each standard block should have the following options:**

 - [x] background color (white, black, purple, green, yellow, salmon, blue, etc)
 - [x] text color (black, white)
 - [x] background image (default opacity, variable opacity or fully opaque)
 - [x] no border option
 - [x] no padding option
 - [x] no margin option
 - [x] hero option (basically more padding on top and bottom) - could be consolidated with no. 5
 - [x] text-alignment
 - [x] easy defaults
 - [x] should support no selection or null
 - [x] button link - external / internal with target 

There is one abnormal block type - the link block (which is basically a regular block with all its options, wrapped in a link). A link block should have centered uppercase text with black link color and white background behind it. It should always have an image background. The bg image goes away on hover.

Another variation of the link block is the kind of button we use on the How to Apply page. I think it should be treated either as a variation of the link block or as an extra large button (wrapped in a blank standard block).

A slider block is another one to add. Possibly a tab block in the future too?

**Comment by luetkemj** [comment]
nice. You should post this on Medium.

**Comment by dstrogiy** [comment]
![1380697092809](https://cloud.githubusercontent.com/assets/6132788/6972819/43c3c4e8-d954-11e4-8a7f-5f67d8faebaf.jpg)

**Comment by streeetlamp** [comment]
this is some mighty fine issue writing

**Comment by dstrogiy** [comment]
Also text-alignment

**Comment by luetkemj** [comment]
Shutting this one down

https://www.youtube.com/watch?v=Gev_Phjl764
