### ISSUE TITLE
Social feed broke on social media page

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#111]
http://arts.vcu.edu/redesign2015/connect/social/

![yassss](https://cloud.githubusercontent.com/assets/6132788/8992830/c80b6a26-36ce-11e5-8fc0-be0176f5f1ae.jpg)

**Comment by streeetlamp** [comment]
![popkey-walken-da](https://cloud.githubusercontent.com/assets/1740634/9009888/ea5c4dcc-3771-11e5-97d4-7ce1aba2dc09.gif)
