### ISSUE TITLE
Remove lorem ipsum

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#113]
My directory list has lorem ipsum in the popup. And my middle initial is not a Z.

Don't mind the fabulous photo of though. Top notch.

![screen shot 2015-07-30 at 4 46 00 pm](https://cloud.githubusercontent.com/assets/925980/8994772/5648eabe-36db-11e5-91ee-b6ea69c20e6b.png)

**Comment by streeetlamp** [comment]
i wish you could stay but i guess its best if you weren't in the directory, rip mark

**Comment by luetkemj** [comment]
:(

**Comment by streeetlamp** [comment]
![popkey-sad-cry-t](https://cloud.githubusercontent.com/assets/1740634/9008960/c5d2313e-376b-11e5-9d17-27862d3859fb.gif)
