### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#115]
This page:
http://arts.vcu.edu/redesign2015/faculty/

This link:

![screen shot 2015-07-30 at 10 15 02 pm](https://cloud.githubusercontent.com/assets/925980/8999450/7f252d8a-3708-11e5-8b64-095b6186905d.png)

**Comment by dstrogiy** [comment]
Good find!

**Comment by luetkemj** [comment]
NP - apologies for being a creepy stalker...
