### ISSUE TITLE
Broken Links post-launch

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#118]
- [x] footer - how to apply

**Comment by dstrogiy** [comment]
- [ ] all links leading to Andrew's arts/research site need to be manually fixed

**Comment by dstrogiy** [comment]
- [ ] htaccess redirect for /alumni should be removed

**Comment by dstrogiy** [comment]
- [ ] http://arts.vcu.edu/current-students/scholarships/ - all the links are broken

**Comment by dstrogiy** [comment]
- [ ] http://arts.vcu.edu/research-innovation/grants/graduate-research-grant/
- [ ] http://arts.vcu.edu/research-innovation/grants/exploratory-research-grant/
- [ ] http://arts.vcu.edu/research-innovation/grants/american-academy-in-rome/
- [ ] http://arts.vcu.edu/research-innovation/grants/research-reassignments/
 
all of those have links to application templates broken - might need to check with casey regarding the right file

**Comment by dstrogiy** [comment]
- [ ] homepage - 3 latest news - more link broken

**Comment by streeetlamp** [comment]
open again if we find more
