### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#119]
This page: http://arts.vcu.edu/research-innovation/
Viewport 700px

![screen shot 2015-08-03 at 8 57 17 am](https://cloud.githubusercontent.com/assets/925980/9037929/197fa542-39be-11e5-94c2-351505623274.png)

**Comment by dstrogiy** [comment]
At 700px it's very likely to a be a tablet that doesn't support hover, so I took it out completely. e940b11
