### ISSUE TITLE
Implement Dan's Super Duper News Layout

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#127]
http://arts.vcu.edu/blog-2/

Make sure category archives and all that also match
Also probably tweak single views some 

Should single posts have a link back to the main News page? I think so

**Comment by streeetlamp** [comment]
The smaller posts at the end of the page should have a shorter excerpt length 
—
Maybe look at setting a max height + white gradient on the bottom so we can a even grid

**Comment by dstrogiy** [comment]
The layout is implemented

![savageup](https://cloud.githubusercontent.com/assets/6132788/9172861/4d775efe-3f44-11e5-9d8d-09ed8a7baa81.gif)
