### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#131]
When using search, some links are rendered with via https, which causes json to break because of secure connection. Looks like it's mostly affecting blog results.

**Comment by streeetlamp** [comment]
fixed everywhere i could find 

apparently we do support HTTPS which is great but that means we need to allow for resources/content to be loaded over HTTPS if requested. in the future when using an absolute URL make sure its '//content.com/image.jpg' and not 'http://content.com/image.jpg' so the browser can decide which protocol to use.
