### ISSUE TITLE
Blog white gradient on iphones

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#132]
Let's remove that, since it's not rendering correctly on mobile

![screen shot 2015-08-10 at 12 36 11 pm](https://cloud.githubusercontent.com/assets/6132788/9176971/65c72706-3f5c-11e5-9e56-a37587d79adb.png)

**Comment by streeetlamp** [comment]
fixed, was just a problem with using 'transparent' in the style. changed it to rbga
