### ISSUE TITLE
Search term * value v placeholder

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#134]
When you search on the arts site the term is dropped into the searchform as a placeholder on the results page.

When I tried to enter a new search my first inclination was to double click on the term to hightlight it (as I had entered in myself previously) in order to delete and type a new one.

This is not possible as it is a placeholder.

Unexpected behavior.

Something to think about - possibly AB test or something.

**Comment by dstrogiy** [comment]
Now it's just a value - everyone wins

![giphy](https://cloud.githubusercontent.com/assets/6132788/9234911/c69abc6a-4109-11e5-8938-7f718494ed89.gif)
