### ISSUE TITLE
Calendar Site - 404

### ISSUE THREAD

**Issue by caseferg** [VCUarts/vcuarts2015#138]
Not a priority at all, but could we make the 404 error on the calendar site similar to what we do on the main arts site? At the very least, remove "this is the 404 template".

![calendar404](https://cloud.githubusercontent.com/assets/12819381/9876531/c73dc032-5b84-11e5-9be8-bd00439dc9d8.png)

**Comment by streeetlamp** [comment]
whoops, thanks casey!

**Comment by dstrogiy** [comment]
![screen shot 2015-10-06 at 9 47 00 am](https://cloud.githubusercontent.com/assets/6132788/10310285/36b9fec2-6c0f-11e5-8131-cb3bd7e5746c.png)

right on
