### ISSUE TITLE
Can we use something like Trello to provide a checklist for admissions?

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#2]
Can we have a checklist that folks can import or somehow use as a boilerplate?

- [ ] talk to admissions about the idea

**Comment by streeetlamp** [comment]
What about just using HTML checkboxes and we can save progress / state in localstorage?

**Comment by streeetlamp** [comment]
And have an awesome print stylesheet

**Comment by luetkemj** [comment]
Definitely need banging print styles

**Comment by luetkemj** [comment]
Re local storage or trello... maybe both? The only concern with local storage is that it only works on one machine right?

Still a super cool feature to have and not a lot of work to implement.

**Comment by luetkemj** [comment]
Should probably chat with Admissions about it to see if they would even want this feature.

**Comment by luetkemj** [comment]
Totally possible: 

lifehacker has some great links in here to templates and some cool ways of using the thing.

http://lifehacker.com/how-to-use-trello-to-organize-your-entire-life-1683821040

**Comment by luetkemj** [comment]
more trello how tos

http://computers.tutsplus.com/tutorials/everything-you-need-to-know-to-work-productively-in-trello--cms-21450

**Comment by streeetlamp** [comment]
![6603dc5a9292104b44c349b85b5aaf7a-5-crazy-fan-theories-that-make-total-sense](https://cloud.githubusercontent.com/assets/1740634/6965168/68919804-d91d-11e4-80ad-6b31ebbb6a8c.jpg)

**Comment by dstrogiy** [comment]
![1-arkuqdwjaigo-1-1](https://cloud.githubusercontent.com/assets/6132788/7711161/b716b5fc-fe36-11e4-94af-14f22db3c4e0.jpg) ^ done
