### ISSUE TITLE
Image blocks have padding on top

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#24]
This is due to WP adding Ptags around the images in there.

![screen shot 2015-04-10 at 10 51 40 am](https://cloud.githubusercontent.com/assets/925980/7090243/a7ce923a-df6f-11e4-8f28-f6b417c2b3bc.png)

**Comment by dstrogiy** [comment]
![fixed-magazine-issue-2-winter-2008](https://cloud.githubusercontent.com/assets/6132788/7093773/1b26c8aa-df8a-11e4-8325-c13eb9fa947c.jpg)
