### ISSUE TITLE
SCSS refactor

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#3]
Should nuke the modules folder and reexamine the rest.

Only bring in new bits as we need them

**Comment by luetkemj** [comment]
won't be so cut and dry.

Nuking everything and then pulling stuff back in is gonna be too much double work. I vote we bring in everything and refactor as needed.

**Comment by streeetlamp** [comment]
alrighttt 

![7kiqqxz](https://cloud.githubusercontent.com/assets/1740634/6964712/db0f52a8-d919-11e4-9205-7475b93a052e.gif)
