### ISSUE TITLE
Formats to add

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#35]
- [ ] headline-bg class
- [ ] no-margin class
- [ ] gradient to the block settings option

**Comment by dstrogiy** [comment]
^ there's a "margin-none" and "nomargin" classes currently

**Comment by luetkemj** [comment]
^^ Yep, we just need to add them in the formats dropdown for easy access

**Comment by dstrogiy** [comment]
^^^ yaaaas

**Comment by luetkemj** [comment]
@dstrogiy do you want any of these things anymore???????

For the non techy folks.....

**Comment by dstrogiy** [comment]
nah, I think we should be good with just an input bar, since it's gonna be admins

**Comment by dstrogiy** [comment]
or are you referring to the wysiwig?

**Comment by luetkemj** [comment]
Yeah, I guess... these aren't hard for y'all to add later. Let's get your stuff set and have Casey start working with it. If we need it we'll know then

**Comment by dstrogiy** [comment]
![solid_brick_3](https://cloud.githubusercontent.com/assets/6132788/7431154/b01c1018-efe9-11e4-8820-bf110986d638.jpg)
