### ISSUE TITLE
Secondary Nav Overflow Scroll

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#37]
This kind of interaction on mobile especially instead of breaking 
http://davidecalignano.it/css-trick-to-reproduce-glimpse-on-native-scroll/

**Comment by streeetlamp** [comment]
the apple store is a good example fyi 
http://store.apple.com/us-hed/mac

**Comment by dstrogiy** [comment]
We're not doing this anymore, right

**Comment by streeetlamp** [comment]
correcto
