### ISSUE TITLE
BG gradient overlay not 100% height

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#4]
changed how we do the bg overlay for images.

Allows for dynamic images with ACF but it's causing a bug where the overlay only goes partway down the page.

**Comment by streeetlamp** [comment]
fixed thanks to psuedo elements
https://github.com/VCUarts/vcuarts2015/commit/780fe4bdf05c1eb2a5fc3acc8abd9ffac44aa01a
