### ISSUE TITLE
Hyphenator

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#41]
Need to fix this but not really have hyphens everywhere...

![screen shot 2015-04-24 at 3 01 32 pm](https://cloud.githubusercontent.com/assets/925980/7326392/ece39ce8-ea92-11e4-804b-1082da255ec0.png)

**Comment by dstrogiy** [comment]
Since this is the only instance of the overflow happening, I think we can use the &shy; tag for a soft hyphen in this block.
