### ISSUE TITLE
Breadcrumbs?

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#44]
Should we have breadcrumbs?
I feel like they will be redundant overall, but some sections (specifically the "How to Apply") could benefit from them
![breadcrumbs2](https://cloud.githubusercontent.com/assets/6132788/7379075/1d0c3f1c-edc0-11e4-8103-b769104b472c.jpg)

**Comment by streeetlamp** [comment]
Mark and I talked about this the other day and we agreed the benefit probably isn't worth how tricky they could be to implement
