### ISSUE TITLE
Video Block

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#45]
Should have a block for responsive video embeds that you can just paste in a youtube/vimeo/etc link

**Comment by luetkemj** [comment]
If we use an html block and embed responsively we are all set.

http://embedresponsively.com/

**Comment by streeetlamp** [comment]
1 - We could just that part automatically though instead of copying the video URL -> visiting http://embedresponsively.com/ - > pasting copied text 
2 - If someone forgets and just pastes in a youtube link

**Comment by streeetlamp** [comment]
also http://fitvidsjs.com/

**Comment by dstrogiy** [comment]
![7f77546945f948560cdc26b12b99d5ccd390c2e39d2849d3423ae7608dac066a](https://cloud.githubusercontent.com/assets/6132788/7636334/b03842f6-fa34-11e4-9243-ff487f2d77cc.jpg) just add .video to any block and we good
