### ISSUE TITLE
Image paths after import

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#46]
FYI. All posts imported from the old site have retained their URL structure. This shouldn't cause any trouble so long as directories etc don't change. 

But it could.... 

Be aware when launching.

**Comment by streeetlamp** [comment]
They are retaining the actual URL they are living at or just like image URLs inside of then? 
Also curse WP to hell for this stuff

**Comment by streeetlamp** [comment]
Note: 
Older VCUarts images point to /uploads/ 
Images are we posted to the dev site point to blogs.dir/uploads/

What happens when this new site goes live?

**Comment by streeetlamp** [comment]
Tested locally and seems to continue chugging along as before. Changing the 'master' site has no effect on where the uploads go. New ones still go to same folder, old ones continue to live where they were.
