### ISSUE TITLE
Blog Todos

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#47]
- [x] remove category from index pages
 - [x] better single post template
 - [x] include the category on single posts
 - [x] have category bg images so singles have something to hook into
 - [x] better archives
 - [x] use proper blog pages not archives on the other blog pages

**Comment by dstrogiy** [comment]
![giphy](https://cloud.githubusercontent.com/assets/6132788/7617109/21bf96d6-f977-11e4-92fe-0b0d3b3e4bbb.gif)

Pretty much done
