### ISSUE TITLE
Publications Template

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#51]
Something instead of ISUU in the backend
![tumblr_mz04tanpri1rjvz5zo1_400](https://cloud.githubusercontent.com/assets/6132788/7473167/ff74e958-f306-11e4-8319-9fc8727f5095.gif)

**Comment by streeetlamp** [comment]
pdf.js to the rescue (hopefully) 

random links I collected 
https://github.com/mozilla/pdf.js
http://mozilla.github.io/pdf.js/examples/learning/prevnext.html  
http://www.maxims6n.bget.ru/pdf_books/demo_21.html

**Comment by dstrogiy** [comment]
I think pdf.js is the way to go  👍 👍 👍 👍

**Comment by streeetlamp** [comment]
turn.js is super annoying to implement especially responsively 
ikea does a nice job of their catalogs as a slider type thing 
http://info.ikea-usa.com/Catalog/

**Comment by streeetlamp** [comment]
using issuu for now :)
