### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#52]
We need to have several different kinds of sliders going.

1) Image Slider (with caption support) - that can be used on stuff like the About page, Programs page, etc.

2) Text slider (like the testimonials on Financial Info page and possibly news on homepage)

They need to look extra nice and work through ACF Flexible Content.

**Comment by streeetlamp** [comment]
![screen shot 2015-05-11 at 9 59 53 am](https://cloud.githubusercontent.com/assets/1740634/7566390/7e7045a6-f7c4-11e4-8d40-4aaecffd30a8.png)

**Comment by dstrogiy** [comment]
It would be useful to have an option to add a link to each caption in the feature slider. That way each slide could function as a a giant link. We can style them to match the current link blocks.

**Comment by dstrogiy** [comment]
We good
