### ISSUE TITLE
Use Magnific Popup as a gallery grid instead of fat's zoom.js

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#58]
However, we should keep zoom.js so that we can use it on articles or blocks with one single image that can be expanded.

AFO gallery function (http://arts.vcu.edu/artfoundation/gallery/) is a pretty good example, althought we should add a couple of nice transitions.

**Comment by streeetlamp** [comment]
doooone 

![4l1z0lf](https://cloud.githubusercontent.com/assets/1740634/7706188/d7107b74-fe16-11e4-9b3e-98eef4d4d449.gif)
