### ISSUE TITLE
Last Modified Footer Alternative

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#60]
It was never great to begin with but its throwing errors now for using deprecated functions so we should find an alternative or roll our own. 

Specifically the deprecated function is 'add_contextual_help'

**Comment by streeetlamp** [comment]
Suggesting switching to this
https://wordpress.org/plugins/site-last-modified/

**Comment by luetkemj** [comment]
there is a function for this y'all should use

no plugin needed

https://codex.wordpress.org/Function_Reference/the_modified_date

**Comment by streeetlamp** [comment]
we could use that for individual posts but we usually just display the last modified date of any content throughout the site.

**Comment by dstrogiy** [comment]
Using https://wordpress.org/plugins/site-last-modified/ - seems to be working good.
