### ISSUE TITLE
Accordion Block Type

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#62]
To build out accordions on fleek
![hohneraccordion](https://cloud.githubusercontent.com/assets/6132788/7861788/2b0565fe-0520-11e5-9a22-9981559aac60.gif)

Example - http://arts.vcu.edu/redesign2015/connect/

**Comment by streeetlamp** [comment]
doing this today

![giphy](https://cloud.githubusercontent.com/assets/1740634/7861951/07fa830e-0521-11e5-94ec-03b8f843a85f.gif)

**Comment by streeetlamp** [comment]
this is finally basically done i guess 

![lc6isk6](https://cloud.githubusercontent.com/assets/1740634/7891579/cbf18352-061b-11e5-920b-e23db515a27c.gif)
