### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#63]
- [x] Need something displayed for when there're no posts found
- [x] Needs caching on the server
- [x] There's a 404 bug for the avatars at the moment
- [x] Bio links
- [x] Dept Filter Fixes
- [ ] Bio Permalinks

**Comment by streeetlamp** [comment]
- [ ] Bio links

**Comment by dstrogiy** [comment]
Currently the directory has a filter all of departments - http://arts.vcu.edu/redesign2015/connect/directory/
What about office of the dean? I feel like people might want to have that option as well. Unless it's already a part of "All departments"?

**Comment by streeetlamp** [comment]
I'll add the Deans Office, I think a few of the filters are not matching up with the proper category either due to misplaced hypens, etc. so I need to fix that too

**Comment by dstrogiy** [comment]
Word

**Comment by PeytonSorah** [comment]
- [x] Research + Entrepreneurship
- [x] Human Resources
- [  ] Development (up to Julia Carr)

**note: some people work in more than one department (ie Susan Martin)

**Comment by dstrogiy** [comment]
![screen shot 2015-06-10 at 1 39 05 pm](https://cloud.githubusercontent.com/assets/6132788/8089482/245c2c64-0f76-11e5-9bae-4e607d2fe8c3.png)

Dept title is a bit redundant haha

**Comment by dstrogiy** [comment]
- [ ] thumbs to move above description on mobile

**Comment by dstrogiy** [comment]
![screen shot 2015-06-22 at 4 07 16 pm](https://cloud.githubusercontent.com/assets/6132788/8291644/cccf642a-18f8-11e5-8f24-2e8a1cd204d7.png)

Kinda random that when you search for "dean", a blank screen shows up instead of "no results found"

**Comment by streeetlamp** [comment]
oh yeah, i noticed that today too

**Comment by dstrogiy** [comment]
Is it possible to search using department title in the search area as well? I could some people attempting to use the search in this way.

![screen shot 2015-06-24 at 3 39 14 pm](https://cloud.githubusercontent.com/assets/6132788/8339676/37111286-1a87-11e5-8e97-06cf9180cfae.png)

**Comment by dstrogiy** [comment]
- [ ] reorder things based on Casey's comments from the other thread

**Comment by dstrogiy** [comment]
- [ ] hide adjuncts
