### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#69]
This thread is for pointing out all the things that need to be fixed in mobile

- [x] Spacing in header
- [x] Smaller headings - h1, h2, h3, h4, page-title
- [x] Remove link underlines
- [x] Padding-none and margin-none are not functioning because of breakpoints
- [ ] background images are messed up

**Comment by dstrogiy** [comment]
- [ ] secondary menu nav should be hidden

**Comment by PeytonSorah** [comment]
- [ ] home: reduce distance to footer
- [ ] about:rankings: mobile ranking chart
- [ ] about:facilities: scrolling is a little tough when passing over google things
- [ ] about:facilities: fix double-click to move between button
- [ ] about:diversity: contact holly treatment
- [ ] about:internships and careers: no content here yet
- [ ] admissions:how to apply: "i am a" seems a little disjointed-consider different treatment?
- [ ] admissions: visit campus: rva all day button seems really tall

- [ ] gray background
- [ ] solution for subnav on interior pages-
can you keep parent (About, etc) above the list of subnavs? right now subnav is highlighted AND parent changes
OR 
get rid of bread crumbs entirely (although they look great on mobile-so preferably not)
- [ ] it is a little strange that some blocks of content/links are butted up against each other and others have margins-perhaps this could be made more consistent? 
- [ ] conversation about consistency with buttons-there are a lot of type sizes 
- [ ] footer spacing

**Comment by dstrogiy** [comment]
- [ ] mobile popups lol

![bio](https://cloud.githubusercontent.com/assets/6132788/8134053/3718d41c-10fa-11e5-806b-e2e1ece48fc6.jpg)

**Comment by dstrogiy** [comment]
Mobile is all good really, except stuff like search - so we can point out to specific bugs when we find them
