### ISSUE TITLE
ACF Notes / Thoughts 

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#7]
Streamlining the backend by moving the default content editor into the ACF area
http://www.advancedcustomfields.com/resources/moving-wp-elements-content-editor-within-acf-fields/

**Comment by luetkemj** [comment]
You had mentioned some plugins for collapsing things that would be nice also.

Fashion can get unwieldy on long pages

**Comment by streeetlamp** [comment]
^ https://github.com/urre/acf-fold-flexible

**Comment by streeetlamp** [comment]
nice repo of ACF plugins
https://github.com/reyhoun/awesome-acf

**Comment by streeetlamp** [comment]
do ACF fields not show up in WP-API feeds by default? 
https://github.com/times/acf-to-wp-api

**Comment by luetkemj** [comment]
^ no they don't but I have a function that handles it

```php
		/**
		 * Make sure that all custom fields get attached to wp-api json output
		 *
		 * @since    1.0.0
		 */
		function wp_api_encode_acf($data,$post,$context){
			$data['meta'] = array_merge($data['meta'],get_fields($post['ID']));
			return $data;
		}
		if( function_exists('get_fields') ){
			add_filter('json_prepare_post', 'wp_api_encode_acf', 10, 3);
		}
```

**Comment by luetkemj** [comment]
Holy wow that'a lot of ACF plugins
