### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#71]
- [x] initialize the base slider as default-slider
- [x] change feature-bottom to feature and init when needed
- [x] display image as background-cover via css instead of inline img

**Comment by streeetlamp** [comment]
![bo8tenn](https://cloud.githubusercontent.com/assets/1740634/8064032/1537b5d0-0ea6-11e5-9c5b-8fcd7a025ef0.gif)
