### ISSUE TITLE
Alumni Bios

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#73]
- [x] Import existing bios from Ester

Bios should probably live under Careers page

- [x] Alumni Custom Post Type
- [x] Implement a new look for bios
- [x] Add a link to add a new bio under I Am A > Alumni page
- [x] Functionality for displaying alumni with multiple degrees and graduation years

**Comment by streeetlamp** [comment]
Bios will live on a sub page of careers, so /about/careers/alumni/ for example

**Comment by streeetlamp** [comment]
Alumni Bios should be a custom post type on the new site also

**Comment by streeetlamp** [comment]
Some alumni have multiple degrees and graduation years (like undergrad degree and grad degree). Currently we are just spitting out one

**Comment by dstrogiy** [comment]
![screen shot 2015-06-15 at 1 24 08 pm](https://cloud.githubusercontent.com/assets/6132788/8165860/d573df08-1361-11e5-9d1a-327dab11bd3a.png) some thumbs are cut lol

**Comment by dstrogiy** [comment]
some thumbs are missing ┐(‘～`；)┌

![screen shot 2015-06-17 at 10 36 34 am](https://cloud.githubusercontent.com/assets/6132788/8209753/c04694b4-14dc-11e5-86ae-70d68b92a217.png)

**Comment by dstrogiy** [comment]
Can't figure it how to get a link to the alumni category working - on the alumni single page - but we need one

**Comment by streeetlamp** [comment]
@dstrogiy gotchu, added

**Comment by dstrogiy** [comment]
Yasss

**Comment by dstrogiy** [comment]
Alumni Bios are good 
![giphy-1](https://cloud.githubusercontent.com/assets/6132788/8238297/a8283680-15c2-11e5-9187-60d8ef33d3a6.gif)
