### ISSUE TITLE
Admissions Section

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#74]
- [x] Add overview link to main nav
- [x] Add a link to "How to get VIP" to the last box on every checklist page
- [x] Replace the current intl link in every checklist with http://international.admissions.vcu.edu/apply/undergraduate/
- [x] Slider opacity - hard to read
- [ ] Add Molly Roberts to admissions directory - they'll send info
- [ ] Need an overview section on how to apply for former students - they'll send info
- [ ] Benefits of art school within university verbiage - add somewhere on the site
- [x] List of departments that offer minors with a contact us for more info CTA => possibly on programs page or somewhere else
- [ ] Possibly a contact form just for admissions?
- [x] Photosphere to Richmond page?
- [x] Pull photos for facilities from #FacilitiesFriday and vcuarts instagram
- [x] Give admissions people access to site
- [x] Send them a link to all existing photospheres

**Comment by dstrogiy** [comment]
- [ ] Art Foundation - modify link in the how to apply => freshman section to look like the rest of box grid, full width

**Comment by streeetlamp** [comment]
Grace pulled some photospheres from around Richmond that she thinks would be nice for the Richmond page, we may add or subtract as we see fit. Maybe it's a simple gallery of thumbnails that each launch their respective photosphere popup 

https://www.google.com/maps/views/u/0/view/107468083806180807293/gphoto/6127440176746124082?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=146&pitch=134&fovy=75

https://www.google.com/maps/views/u/0/view/115202695109280717517/gphoto/5924205741109441234?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=92&pitch=84&fovy=75

https://www.google.com/maps/views/u/0/view/109474858809754628796/gphoto/5881209444663414818?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=253&pitch=88&fovy=75

https://www.google.com/maps/views/u/0/view/100761477255457491662/gphoto/6052588934768731074?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=245&pitch=90&fovy=75

https://www.google.com/maps/views/u/0/view/114594959462943561935/gphoto/6108828144010724370?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=83&pitch=78&fovy=75

https://www.google.com/maps/views/u/0/view/106301561718984125678/gphoto/6001974216484616338?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=273&pitch=89&fovy=75

https://www.google.com/maps/views/u/0/view/113636337396936300854/gphoto/6004761148888577650?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=51&pitch=97&fovy=75

https://www.google.com/maps/views/u/0/view/112648977116934101278/gphoto/5944285707518750898?gl=us&loc=0x89b111095799c9ed:0xbfd83e6de2423cc5&heading=107&pitch=78&fovy=75

**Comment by dstrogiy** [comment]
I like the gallery idea, I'll work on that

**Comment by dstrogiy** [comment]
Well let's assume that admissions is all done, unless they reach out to us with something specific
![giphy-1](https://cloud.githubusercontent.com/assets/6132788/8433289/d0090c02-1f12-11e5-8cea-3663dcddcedf.gif)
