### ISSUE TITLE
New About > Overview page

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#75]
Box for rankings
Box for Accreditation
Dean's Letter
Student Experiences

**Comment by dstrogiy** [comment]
I put together some initial things - http://arts.vcu.edu/redesign2015/about/
I suggest we do Joe's letter via a popup ಠ_ಠ

**Comment by streeetlamp** [comment]
Yes lets pop it up !

**Comment by dstrogiy** [comment]
Joe's popping!
Now we wait for new copy from Maryann & Suzanne
