### ISSUE TITLE
Casey's Text & Linking Edits

### ISSUE THREAD

**Issue by caseferg** [VCUarts/vcuarts2015#78]
- [x] All instances of "U.S. News & World Report" should be: in italics, should have "." in between US and should use an amp (&) and not have "and" spelled out.
- [x] On "Connect", Suzanne should be listed first under Communications.
- [x] On "Connect", remove Anderson Gallery.
- [x] On "Connect", Kelly Kerr's title should be Director of Events and Sponsorships
- [x] On "Connect", add Louie A. Correa, Associate Director of Development, 804 828 6081, lacorrea@vcu.edu
- [x] On "Connect', David Holland's title should be "Program Director for Venture Creation - da Vinci Center"
- [x] On "Connect", add Molly Roberts under Admissions as an Admissions Counselor, 804 828 6699, robertsme5@vcu.edu
- [x] On "Connect", remove Carrie Culpepper from ICA.
- [x] On "Connect", remove Allyson Vandstone as the Dean of VCUQatar. She's been replaced by Akel I. Kahera, +974 4402 0682, akahera@vcu.edu
- [ ] On "Connect", Deans should be listed at the top of that list.
- [x] On "Connect", Art Education, Sara Wilson McKay is the chair's full name.
- [x] On "Connect", the new Fashion chair is Patricia Brown (no contact info ready yet).
- [x] On "Connect", Photo & FIlm, Sasha Waters Freyer (I think three-named folks are an issue here).
- [x] On "Connect", Sculpture, Matt King's title should be Chair and Associate Professor
- [x] On "Connect", Theatre, Ron Keller should be the Chair, rkeller@vcu.edu
- [x] On "Facilities", the addresses look like they should be able to link to a map, but they're # anchored to the page. Should these be going somewhere?
- [x] On "Undergraduate Programs", change the Art Education link to its homepage. Right now, it's the only department that links to an interior page on its site.
- [x] On "Graduate Programs", under Art History remove "Architectural Studies". This program no longer exists.
- [x] On "Graduate Programs", under Resources, update the URL for Graduate Student Travel Grants to the new page in the Grants section.
- FYI: on the "Summer" page, I changed everything to past tense to indicate that the info listed was from the summer of 2015 / which would have already happened by the time this goes live.
- [x] On "Honors", Abbie Werner no longer works here. Update with the correct information - THIS IS ON CASEY, working on finding out the correct contact.
- [x] On "Social Media", Sculpture's tumblr URL is showing a Twitter icon. Also, add @vcusculpture for Instagram.
- [x] On "Give to VCUarts" I made some edits based on a question I posed to Julia. Could someone style the top? They wanted all the development staff to be listed for EACH item - which isn't going to happen, so I thought putting them together at the top made the most sense.
- [x] Suzanne wants the Facilities in alpha order, and I swear to god I can't get FAB in the right place. Please correct.
- [x] Suzanne wants the James Black image and the Shafer Street image to be cropped so they aren't so out of place.
- [x] Suzanne wants this line on the Internships page to be in its own box "Check out below where VCUarts students have held internships." She thinks it's confusing being wrapped in with the general, internship overview text.
- [x] Suzanne wants the following text to appear smaller in the SSP section of the summer page, above the Learn More button, "Sponsored by the departments of Painting + Printmaking and Sculpture + Extended Media."
- [x] Suzanne wants to reorder some things on the I am A...Parent page. She'd like to move the Safety and Richmond (which needs to be done) content down the page, and bump up the Careers and Financial Aid calculator (which I've already done). She'd also like to give the Safety content a muted color (all the same color) so they don't stand out as much as they currently do with the white background. With moving the content around, the boxes styling needs to be updated regardless, so I'll let you play with that.

Note: Re: Connect Page content, is there an eas(ier) way for me to do this? it looks like its pulls from a database. that said, we really only make these types of edits once a year, so maybe its not that big of a deal.

**Comment by dstrogiy** [comment]
Thanks caseferg, I will take a look

**Comment by dstrogiy** [comment]
I'm gonna close this - Casey you are free to open a new one whenever there are edits that need to be on git
