### ISSUE TITLE
Casey's Photo Edits

### ISSUE THREAD

**Issue by caseferg** [VCUarts/vcuarts2015#79]
- [x] About: Replace Internship and Careers images with something that shows arts in practice (does "2013-03-20-10476.jpg" Richmond / Favorites - Extensis read too much like studio work? In the Viewbook we use "gartside_more_stairs.tif" Richmond / Publications - Extensis as the image for Internships)
- [x] About / Internships: Replace background image with a new Macbeth image or the update Internship image from previous item (this current Macbeth image is not licensed for VCU use - use "664A1210color.tif" Cinema / 2014-2015 / Macbeth / VCU Hi Res - Extensis)
- [x] Admissions / How to Apply / Freshman & Transfer: Change the Cinema image - Dr. Tregenza is over that image we're currently using. Use "gartside_more_stairs.tif" Richmond / Publications - Extensis.
- [x] Admissions / How to Apply / Graduate: Change Photography & Film image from Sara Clarken's work to a photo graduate student's work. Use "Cynthia_Henebry-055f.jpg" Richmond / Student Work / Graduate / 2014 MFA Exhibition - Extensis.
- [x] Programs / Undergraduate: Change Cinema image (see above).
- [x] Programs / Summer: I love the image because I thought this project was so wild, but what are our thoughts on nudity?
- [x] Connect / Press: We need Joe's formal image here. I'm thinking that this is a resource to media if they wanted to attribute an image to a quote in a news piece. Use "DSC_8740.tiff" Richmond / Faculty / Seipel - Extensis

**Comment by dstrogiy** [comment]
Thanks caseferg!

**Comment by dstrogiy** [comment]
Re: summer photo - I've figured it would be fine to use since it's hanging right in front of the dean's office lol

I've swtiched it to a different one from summer intensive extensis - it seems to work fine - http://arts.vcu.edu/redesign2015/programs/summer/

**Comment by caseferg** [comment]
I went back and forth about that photo - the work was contained to our building and the site is more external. it was probably fine, but just to be safe. i like what you selected. thanks!
