### ISSUE TITLE
Social Feed

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcuarts2015#84]
Using juicer.io 
—
http://www.juicer.io/api/feeds/vcuarts?per=100&page=1

- [x] unformatted (no links) content 
- [x] clicking anywhere on item takes you to that post/tweet 
- [x] social icon takes you to that vcuarts social profile

**Comment by dstrogiy** [comment]
- [ ] assign separate class to each social link - so we can have hover color to match the social media
