### ISSUE TITLE
Connect page

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#86]
To do:

- [x] rewrite the directory modules to render the whole block via the php file
- [x] use the svg spinner from homepage

The page freezes for a second after data finishes loading, so we should try to fix that :cody:

**Comment by dstrogiy** [comment]
- [ ] fix the freezing

**Comment by streeetlamp** [comment]
boom
- fuck WP emoji js 
- one way data binding is all we need
- disable angular debugging info
