### ISSUE TITLE
News & Announcements, Social Wall

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#87]
### News & Announcements
http://arts.vcu.edu/redesign2015/category/news/
Now that we have a feed working on the homepage, we should get the sidebar feed working as well.
- [x] get the sidebar feed working

### Social Wall
We also need to figure out where to stick the social wall page. There's currently a social media page, but it's just a bunch of links to departments' accounts.
- [ ] figure out the social wall/social media page

### Else
- [x] ..
- [x] profit!

**Comment by dstrogiy** [comment]
We also gotta figure out how to sync the news that were published on the current site since the last sync.

**Comment by dstrogiy** [comment]
Maybe it's a good idea to do it manually and also introduce a featured image field for the new posts? That way we can grab it for the feed on the homepage.

**Comment by dstrogiy** [comment]
![current](https://cloud.githubusercontent.com/assets/6132788/8455526/5494416a-1fd3-11e5-9c2f-2520730e24bc.png)

let's limit some characters

**Comment by dstrogiy** [comment]
^ wrong image

**Comment by dstrogiy** [comment]
![screen shot 2015-07-01 at 9 09 24 am](https://cloud.githubusercontent.com/assets/6132788/8455546/8088054a-1fd3-11e5-91f4-2774c2f804f8.png)

Let's limit some characters

**Comment by streeetlamp** [comment]
characters be limited yo

**Comment by dstrogiy** [comment]
All good
![giphy](https://cloud.githubusercontent.com/assets/6132788/8461723/a74cb35a-1ffc-11e5-9bce-0697dfc1a0b9.gif)
