### ISSUE TITLE
Scholarships page for current students

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#88]
Currently it's pulled from filemaker on app sever. Need a solution for the new site.

**Comment by streeetlamp** [comment]
Spitting out that json 
ex: http://app.art.vcu.edu/scholarships/scholarships2015.php?dept=D004

department codes:
Art Hist - D004
Cinema - D006
GDES - D007
Fashion - D008
ID - D009
Craft - D010
Painting - D011
Sculpture - D012
KI - D013
Music - D014
Theatre - D015
Dance - D016
AFO - D017
Art Ed - D018
CA - D019

**Comment by streeetlamp** [comment]
![xpcim](https://cloud.githubusercontent.com/assets/1740634/8679944/fadb7194-2a2b-11e5-9d91-1f2656412f91.gif)
