### ISSUE TITLE
What are we gonna call these block things in the admin?

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/vcuarts2015#9]
So we need to have proper names for 

 * the entire wrapping metabox
 * the wrapping for each row
 * the wrapping for each column
 * each individual block

Names should be clear such that out admins will need minimal help to figure out what's going on.

**Comment by luetkemj** [comment]
![screen shot 2015-04-02 at 12 49 29 pm](https://cloud.githubusercontent.com/assets/925980/6968718/c415766e-d936-11e4-9447-3b2483839667.png)

**Comment by streeetlamp** [comment]
Content Blocks -> Flexible Content (or maybe Flexible Layout)
Layouts -> Row

Not sure what else 'Two Column Group' could be, but to me something like [50:50], [75:25], etc makes more sense.

**Comment by luetkemj** [comment]
> something like [50:50], [75:25], etc makes more sense.

I like that. Had trouble looking at 2 columns [2:1] which just seem like two conflicting langauages

**Comment by streeetlamp** [comment]
One Column -> Full Width
probably

**Comment by luetkemj** [comment]
sounds like this is sorted for now.

We can open issues for individual blocks.
