### ISSUE TITLE
Social wall on mobile

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/vcuarts2015#98]
![screen shot 2015-07-24 at 10 41 21 am](https://cloud.githubusercontent.com/assets/6132788/8876904/97a7de10-31f0-11e5-9379-4f49694e61ed.png)

we got a small overflow going

**Comment by streeetlamp** [comment]
![5rhfbdr](https://cloud.githubusercontent.com/assets/1740634/8878010/a6ca3298-31f6-11e5-9243-227e7ed11760.gif)
